; Enciende los 2 leds conectados en RB0 Y RB1
    
    LIST P=18F4550

    #INCLUDE <P18F4550.INC>
    
    ;CONFIG1L dir 300000h 	20
    ;CONFIG	PLLDIV=1	 ; 
    ;CONFIG	CPUDIV=OSC1_PLL2 ;CUANDO SE USA XTAL	
    ;CONFIG	USBDIV=2

    ;CONFIG1H dir 300001h	08
    CONFIG	FOSC=INTOSCIO_EC ;OSCILADOR INTERNO, RA6 COMO PIN, USB USA OSC EC
    CONFIG	FCMEN=OFF        ;DESHABILITDO EL MONITOREO DEL RELOJ
    CONFIG	IESO=OFF

    ;CONFIG2L DIR 300002H	38
    CONFIG	PWRT=ON          ;PWRT HABILITADO
    CONFIG  BOR=OFF		 ;BROWN OUT RESET DESHABILITADO
    CONFIG BORV=3		 ;RESET AL MINIMO VOLTAJE NO UTILZADO EN ESTE CASO
    CONFIG	VREGEN=ON	 ;REULADOR DE USB ENCENDIDO

    ;CONFIG2H DIR 300003H	1E
    CONFIG	WDT=OFF          ;WACH DOG DESHABILITADO
    CONFIG WDTPS=32768      ;TIMER DEL WATCHDOG 

    ;CONFIG3H DIR 300005H	81
    CONFIG	CCP2MX=ON	 ;CCP2 MULTIPLEXADAS CON RC1	
    CONFIG	PBADEN=OFF       ;PUERTO B PINES DEL 0 AL 4 ENTRADAS DIGITALES
    CONFIG  LPT1OSC=OFF	 ;TIMER1 CONFIURADO PARA OPERAR EN BAJA POTENCIA
    CONFIG	MCLRE=ON         ;MASTER CLEAR HABILITADO

    ;CONFIG4L DIR 300006H	81
    CONFIG	STVREN=ON	 ;SI EL STACK SE LLENA CAUSE RESET		
    CONFIG	LVP=OFF		 ;PROGRAMACIÒN EN BAJO VOLTAJE APAGADO
    CONFIG	ICPRT=OFF	 ;REGISTRO ICPORT DESHABILITADO
    CONFIG	XINST=OFF	 ;SET DE EXTENCION DE INSTRUCCIONES Y DIRECCIONAMIENTO INDEXADO DESHABILITADO

    ;CONFIG5L DIR 300008H	0F
    CONFIG	CP0=OFF		 ;LOS BLOQUES DEL CÒDIGO DE PROGRAMA
    CONFIG	CP1=OFF          ;NO ESTAN PROTEGIDOS
    CONFIG	CP2=OFF		 
    CONFIG	CP3=OFF

    ;CONFIG5H DR 300009H	C0
    CONFIG	CPB=OFF		 ;SECTOR BOOT NO ESTA PROTEGIDO
    CONFIG	CPD=OFF		 ;EEPROM N PROTEGIDA

    ;CONFIG6L DIR 30000AH	0F
    CONFIG	 WRT0=OFF	 ;BLOQUES NO PROTEGIDOS CONTRA ESCRITURA
    CONFIG	 WRT1=OFF
    CONFIG	 WRT2=OFF
    CONFIG	 WRT3=OFF

    ;CONFIG6H DIR 30000BH	E0
    CONFIG	 WRTC=OFF	 ;CONFIGURACION DE REGISTROS NO PROTEGIDO
    CONFIG	 WRTB=OFF	 ;BLOQUE BOOTEBLE NO PROTEGIDO
    CONFIG	 WRTD=OFF	 ;EEPROMDE DATOS NO PROTGIDA

    ;CONFIG7L DIR 30000CH	0F
    CONFIG	 EBTR0=OFF	 ;TABLAS DE LETURA NO PROTEGIDAS
    CONFIG	 EBTR1=OFF
    CONFIG	 EBTR2=OFF
    CONFIG	 EBTR3=OFF

    ;CONFIG7H DIR 30000DH	40
    CONFIG	 EBTRB=OFF	 ;TABLAS NO PROTEGIDAS
    
    #DEFINE	LED0	PORTB, 0, 0
    #DEFINE	LED1	PORTB, 1, 0
    #DEFINE	LED2	PORTB, 2, 0
    #DEFINE	LED3	PORTB, 3, 0
    #DEFINE	LED4	PORTB, 4, 0
    #DEFINE	LED5	PORTB, 5, 0
    #DEFINE	LED6	PORTB, 6, 0
    #DEFINE	LED7	PORTB, 7, 0
    
    
    ORG		.0
    
INICIO
    CLRF    PORTB, 0	; Limpiar PORTA   
    CLRF    TRISB	; Configura TRISD 0000 0000 (8 Salidas)
    
    MOVLW   .7		; Asigna 7 Decimal a W
    MOVWF   CMCON, 0	; Asigna 111 (7 Binario) a CMCON para indicar que
			; Esta apagado el comparador de voltaje
    
    MOVLW   B'11000111'	; Configuracion de T0CON
    MOVWF   T0CON

MAIN
    BCF	    LED7	; Apaga el LED7
    BSF	    LED0	; Enciende el LED0
    CALL    DELAY	; Llama a la rutina de delay
    BCF	    LED0	; Apaga el LED0
    BSF	    LED1	; Enciende LED1
    CALL    DELAY	; Llama a la rutina de delay
    BCF	    LED1	; Apaga el LED1
    BSF	    LED2	; Enciende LED2
    CALL    DELAY	; Llama a la rutina de delay
    CALL    DELAY	; Llama a la rutina de delay
    BCF	    LED2	; Apaga el LED2
    BSF	    LED3	; Enciende LED3
    CALL    DELAY	; Llama a la rutina de delay
    BCF	    LED3	; Apaga el LED3
    BSF	    LED4	; Enciende LED4
    CALL    DELAY	; Llama a la rutina de delay
    BCF	    LED4	; Apaga el LED4
    BSF	    LED5	; Enciende LED5
    CALL    DELAY	; Llama a la rutina de delay
    BCF	    LED5	; Apaga el LED5
    BSF	    LED6	; Enciende LED6
    CALL    DELAY	; Llama a la rutina de delay
    BCF	    LED6	; Apaga el LED6
    BSF	    LED7	; Enciende LED7
    CALL    DELAY	; Llama a la rutina de delay
    BRA	    MAIN	; Regresa a Main

DELAY
    CLRF    TMR0L, 0
    MOVLW   .98		; Asigna 50 a W
ASK 
    CPFSEQ  TMR0L, 0	; Compara el valor de TMR0L y W (50)
    BRA	    ASK		; Llama a la rutina ASK si TMR0L no es 50
    RETURN		; Cuando TMR0L sea 50, sale del ciclo
    END	