; Este prgrama es un sumador en paralelo de 3 bits
; Suma cantidades de 3 bits por lo que el mayor resultado es 14
; La cantidad 1 se encuentra en RA2 RA1 RA0
; La cantidad 2 se encuentra en RA6 RA5 RA4
; El resultado se muestra en PORTB (4 bits de salida)

    LIST P=18F4550

    #INCLUDE <P18F4550.INC>
    
    ;CONFIG1L dir 300000h 	20
    ;CONFIG	PLLDIV=1	 ; 
    ;CONFIG	CPUDIV=OSC1_PLL2 ;CUANDO SE USA XTAL	
    ;CONFIG	USBDIV=2

    ;CONFIG1H dir 300001h	08
    CONFIG	FOSC=INTOSCIO_EC ;OSCILADOR INTERNO, RA6 COMO PIN, USB USA OSC EC
    CONFIG	FCMEN=OFF        ;DESHABILITDO EL MONITOREO DEL RELOJ
    CONFIG	IESO=OFF

    ;CONFIG2L DIR 300002H	38
    CONFIG	PWRT=ON          ;PWRT HABILITADO
    CONFIG  BOR=OFF		 ;BROWN OUT RESET DESHABILITADO
    CONFIG BORV=3		 ;RESET AL MINIMO VOLTAJE NO UTILZADO EN ESTE CASO
    CONFIG	VREGEN=ON	 ;REULADOR DE USB ENCENDIDO

    ;CONFIG2H DIR 300003H	1E
    CONFIG	WDT=OFF          ;WACH DOG DESHABILITADO
    CONFIG WDTPS=32768      ;TIMER DEL WATCHDOG 

    ;CONFIG3H DIR 300005H	81
    CONFIG	CCP2MX=ON	 ;CCP2 MULTIPLEXADAS CON RC1	
    CONFIG	PBADEN=OFF       ;PUERTO B PINES DEL 0 AL 4 ENTRADAS DIGITALES
    CONFIG  LPT1OSC=OFF	 ;TIMER1 CONFIURADO PARA OPERAR EN BAJA POTENCIA
    CONFIG	MCLRE=ON         ;MASTER CLEAR HABILITADO

    ;CONFIG4L DIR 300006H	81
    CONFIG	STVREN=ON	 ;SI EL STACK SE LLENA CAUSE RESET		
    CONFIG	LVP=OFF		 ;PROGRAMACIÒN EN BAJO VOLTAJE APAGADO
    CONFIG	ICPRT=OFF	 ;REGISTRO ICPORT DESHABILITADO
    CONFIG	XINST=OFF	 ;SET DE EXTENCION DE INSTRUCCIONES Y DIRECCIONAMIENTO INDEXADO DESHABILITADO

    ;CONFIG5L DIR 300008H	0F
    CONFIG	CP0=OFF		 ;LOS BLOQUES DEL CÒDIGO DE PROGRAMA
    CONFIG	CP1=OFF          ;NO ESTAN PROTEGIDOS
    CONFIG	CP2=OFF		 
    CONFIG	CP3=OFF

    ;CONFIG5H DR 300009H	C0
    CONFIG	CPB=OFF		 ;SECTOR BOOT NO ESTA PROTEGIDO
    CONFIG	CPD=OFF		 ;EEPROM N PROTEGIDA

    ;CONFIG6L DIR 30000AH	0F
    CONFIG	 WRT0=OFF	 ;BLOQUES NO PROTEGIDOS CONTRA ESCRITURA
    CONFIG	 WRT1=OFF
    CONFIG	 WRT2=OFF
    CONFIG	 WRT3=OFF

    ;CONFIG6H DIR 30000BH	E0
    CONFIG	 WRTC=OFF	 ;CONFIGURACION DE REGISTROS NO PROTEGIDO
    CONFIG	 WRTB=OFF	 ;BLOQUE BOOTEBLE NO PROTEGIDO
    CONFIG	 WRTD=OFF	 ;EEPROMDE DATOS NO PROTGIDA

    ;CONFIG7L DIR 30000CH	0F
    CONFIG	 EBTR0=OFF	 ;TABLAS DE LETURA NO PROTEGIDAS
    CONFIG	 EBTR1=OFF
    CONFIG	 EBTR2=OFF
    CONFIG	 EBTR3=OFF

    ;CONFIG7H DIR 30000DH	40
    CONFIG	 EBTRB=OFF	 ;TABLAS NO PROTEGIDAS


NUM1    EQU  .80 ;Asigna el valor 80 a DAA
NUM2    EQU  .81 ;Asigna el valor 81 a DAA

    ORG  .0

INICIO
    CLRF     PORTA
    CLRF     PORTB
    CLRF     TRISB   ; TB = 0000 0000 (8 Salidas)
    SETF     TRISA   ; TA = 0111 1111 (7 Entradas)
    MOVLW    .15     ; Asigna 15 a W
    MOVWF    ADCON1  ; Asigna 1111 (15 Binario) a ADCON1 para indicar que
		     ; Todas las entradas son digitales

    MOVLW    .7      ; Asigna 7 a W
    MOVWF    CMCON   ; Asigna 111 (7 Binario) a ADCON1 para indicar que
		     ; Esta apagado el comparador de voltaje

SUMA
    MOVF    PORTA, W, 0 ; Asigna el valor de PORTA a W
			; W = 01110111

    ANDLW   B'00000111' ; Aplicar una mascara para obtener el valor de
			; RA0 RA1 RA2

    MOVWF   NUM1, 1     ; Se mueve el valor de W A NUM1


    MOVF    PORTA, W, 0 ; Asigna el valor de PORTA a W
			; W = 01110111

    RRNCF   WREG, F, 0	; W = 10111011
    RRNCF   WREG, F, 0	; W = 11011101
    RRNCF   WREG, F, 0	; W = 11101110
    RRNCF   WREG, F, 0	; W = 01110111

    ANDLW   B'00000111' ; Aplicar una mascara para obtener el valor de
			; RA6 RA5 RA4

    MOVWF   NUM2, 1     ; Se mueve el valor de W A NUM2

    ADDWF   NUM1, W, 1  ; Se suma el valor de W y NUM1 y se almacena en W

    MOVWF   PORTB, 0    ; Mueve el valor de W a PORTB
    GOTO    SUMA

    END
