;Encienda un led en RD0 cuando se presione un botón en RA0. Si el led está 
;encendido y el mismo botón de presiona dos veces seguidas 
;el led debe apagarse. 
    
    LIST P=18F4550

    #INCLUDE <P18F4550.INC>
    
    ;CONFIG1L dir 300000h 	20
    ;CONFIG	PLLDIV=1	 ; 
    ;CONFIG	CPUDIV=OSC1_PLL2 ;CUANDO SE USA XTAL	
    ;CONFIG	USBDIV=2

    ;CONFIG1H dir 300001h	08
    CONFIG	FOSC=INTOSCIO_EC ;OSCILADOR INTERNO, RA6 COMO PIN, USB USA OSC EC
    CONFIG	FCMEN=OFF        ;DESHABILITDO EL MONITOREO DEL RELOJ
    CONFIG	IESO=OFF

    ;CONFIG2L DIR 300002H	38
    CONFIG	PWRT=ON          ;PWRT HABILITADO
    CONFIG  BOR=OFF		 ;BROWN OUT RESET DESHABILITADO
    CONFIG BORV=3		 ;RESET AL MINIMO VOLTAJE NO UTILZADO EN ESTE CASO
    CONFIG	VREGEN=ON	 ;REULADOR DE USB ENCENDIDO

    ;CONFIG2H DIR 300003H	1E
    CONFIG	WDT=OFF          ;WACH DOG DESHABILITADO
    CONFIG WDTPS=32768      ;TIMER DEL WATCHDOG 

    ;CONFIG3H DIR 300005H	81
    CONFIG	CCP2MX=ON	 ;CCP2 MULTIPLEXADAS CON RC1	
    CONFIG	PBADEN=OFF       ;PUERTO B PINES DEL 0 AL 4 ENTRADAS DIGITALES
    CONFIG  LPT1OSC=OFF	 ;TIMER1 CONFIURADO PARA OPERAR EN BAJA POTENCIA
    CONFIG	MCLRE=ON         ;MASTER CLEAR HABILITADO

    ;CONFIG4L DIR 300006H	81
    CONFIG	STVREN=ON	 ;SI EL STACK SE LLENA CAUSE RESET		
    CONFIG	LVP=OFF		 ;PROGRAMACIÒN EN BAJO VOLTAJE APAGADO
    CONFIG	ICPRT=OFF	 ;REGISTRO ICPORT DESHABILITADO
    CONFIG	XINST=OFF	 ;SET DE EXTENCION DE INSTRUCCIONES Y DIRECCIONAMIENTO INDEXADO DESHABILITADO

    ;CONFIG5L DIR 300008H	0F
    CONFIG	CP0=OFF		 ;LOS BLOQUES DEL CÒDIGO DE PROGRAMA
    CONFIG	CP1=OFF          ;NO ESTAN PROTEGIDOS
    CONFIG	CP2=OFF		 
    CONFIG	CP3=OFF

    ;CONFIG5H DR 300009H	C0
    CONFIG	CPB=OFF		 ;SECTOR BOOT NO ESTA PROTEGIDO
    CONFIG	CPD=OFF		 ;EEPROM N PROTEGIDA

    ;CONFIG6L DIR 30000AH	0F
    CONFIG	 WRT0=OFF	 ;BLOQUES NO PROTEGIDOS CONTRA ESCRITURA
    CONFIG	 WRT1=OFF
    CONFIG	 WRT2=OFF
    CONFIG	 WRT3=OFF

    ;CONFIG6H DIR 30000BH	E0
    CONFIG	 WRTC=OFF	 ;CONFIGURACION DE REGISTROS NO PROTEGIDO
    CONFIG	 WRTB=OFF	 ;BLOQUE BOOTEBLE NO PROTEGIDO
    CONFIG	 WRTD=OFF	 ;EEPROMDE DATOS NO PROTGIDA

    ;CONFIG7L DIR 30000CH	0F
    CONFIG	 EBTR0=OFF	 ;TABLAS DE LETURA NO PROTEGIDAS
    CONFIG	 EBTR1=OFF
    CONFIG	 EBTR2=OFF
    CONFIG	 EBTR3=OFF

    ;CONFIG7H DIR 30000DH	40
    CONFIG	 EBTRB=OFF	 ;TABLAS NO PROTEGIDAS
    
    #DEFINE	LED	PORTD, RD0, 0
    #DEFINE	BOTON	PORTA, RA0, 0	
    
    ORG		.0
    
INICIO
    CLRF    PORTA, 0	; Limpiar PORTA
    CLRF    PORTD, 0	; Limpiar PORTD
    
    SETF    TRISA	; Configura TRISA 0111 1111 (7 Entradas)
    CLRF    TRISD	; Configura TRISD 0000 0000 (8 Salidas)
    
    MOVLW   B'1111'	; Asigna 1111 W
    MOVWF   ADCON1, 0	; Asigna 1111 a ADCON1 para indicar que
			; Todas las entradas son digitales
    
    MOVLW   B'111'	; Asigna 111 a W
    MOVWF   CMCON	; Asigna 111 (7 Binario) a CMCON para indicar que
			; Esta apagado el comparador de voltaje
    
    MOVLW   B'11010111'	; Valores de configuracion del T0CON
    MOVWF   T0CON	; Asigna la configracion al T0CON

MAIN
    BTFSS   BOTON	; Consulta si el valor de BOTON es 1 (Boton Presionado)
    GOTO    MAIN	; Si el valor es 0 (Regresa a MAIN)
    GOTO    PUSH_BOTON	; Si el valor es 1 (Enciende el LED)

PUSH_BOTON
    CALL    DELAY	; Llama al DELAY
    BTFSC   BOTON	; Consulta si el valor de BOTON0 es 0
    GOTO    PUSH_BOTON	; Si el valor es 1 (El boton sigue presionado)
    BSF	    LED		; Si el valor es 0 (Enciende el LED)
    GOTO    MAIN	; Regresa a MAIN
    
DELAY
    CLRF    TMR0L, 0
    MOVLW   .10	
    BRA	    ASK		
ASK 
    CPFSEQ  TMR0L, 0
    BRA	    ASK	
    RETURN
    END
    
    